Add capacity to get hub and flipr ids
cnico/flipr-api pull request #2
Opened 2021-02-19 00:22 UTC by AntorFr

Create search_all_ids() returning all filpr and hub ids (in a dict of list)
Create search_hub_ids to get hub id

2021-02-19 17:38 UTC, cnico commented on src/flipr_api/client.py
> +        results = {"flipr":[],"hub":[]} # type: Dict[str,List[str]]
Formatage "black" à corriger selon le contrôle pre-commit de nox.

2021-02-19 17:38 UTC, cnico commented on src/flipr_api/client.py
> +            results["hub"] = [str(item["Serial"]) for item in json_list if item["ModuleType_Id"]==2]
Formatage "black" à corriger selon le contrôle pre-commit de nox.

2021-02-19 17:40 UTC, cnico requested changes
Il faudrait juste corriger les contrôles de mise en forme détectés par la commande "nox" : j'en ai indiqué quelques-uns dans les commentaires et il y en a aussi de petits au niveau de la doc.

2021-02-19 18:03 UTC, cnico commented
Salut @AntorFr,
Merci pour ta PR, je n'ai pas de Flipr Hub donc je ne suis pas tombé sur le cas que tu as ajouté pour récupérer les hub_id.
Je te laisse corriger les points de mise en forme détectés par la commande "nox" comme indiqué dans la revue et puis je merge tout ça.
Je peux faire une v1.2.0 de la librairie et la republier sur pypi si tu veux, dis moi si tu as d'autres modifications à ajouter pour récupérer des données ou des actions via le hub avant de faire une nouvelle version...
J'imagine que tu comptes utiliser ça avec homeassistant comme moi. Pour information, j'ai réalisé une intégration que j'ai proposé à intégrer à homeassistant (cf : https://github.com/home-assistant/core/pull/46582) et j'attends que les mainteneurs fassent la revue et valident ma PR. Si tu veux regarder le code, c'est dans la branche "flipr-integration" de mon fork du core de homeassistant. J'ai testé et ça marche niquel avec mon flipr (les entités de température, chlore et autre remontent bien dans homeassistant). Il ne manque que le merge et une release de homeassistant pour passer en production. Note au passage que j'ai aussi fait une PR sur la documentation.
Pour le Hub, je n'ai pas trop regardé ce que ça fait mais il me semble le hub fait l'équivalent d'un sonoff basic flashé via tasmota (j'utilise ça perso). J'imagine qu'il faudrait ajouter à l'intégration flipr les fonctionnalités du hub (des services ou actions) pour pouvoir actionner le hub via homeassistant en passant par l'api rest... je te laisse creuser tout ça.

Merci encore pour ta contribution.

Nico,

2021-02-19 22:40 UTC, AntorFr commented
Merci pour tes retours ... je débute un peu (beaucoup) avec tout ces outils de lint et de review. Normalement cette fois ce devrais etre bon.

Pas besoin de faire une nouvelle version de la lib. il faut que je crée les fonction pour piloter le hub (passage sur les differents modes : manuel / planning / auto + en manuel faire un On / Off.

mon but est bien de l'utiliser dans Home Assistant, et j'avais rien trouvé comme integration mais c'était pourtant visiblement la (juste un peu caché).

En tout cas encore merci pour ton aide et je te tiens au courant. N'hesites pas si tu as des conseils je suis preneur. Je suis loin d'etre un pro codeur, et mon spot habituel c'est plutôt pandas que python natif... mais c'est bien c'est l'occasion de progresser.

bonne soirée.

2021-02-20 01:39 UTC, AntorFr commented
Et voila, J'ai rajouté les commandes pour pouvoir récupérer l'etat / changer l'etat du Hub.
pour ma part c'est complet par rapport a mes besoins. Maintenant il faut que je regarde ton integration pour rajouter le hub dedans ;-)

Sebastien

2021-02-20 20:53 UTC, cnico approved these changes
Revue globalement OK. 
Il reste un problème avec nox : une erreur remonte sur un cas normalement impossible de booléen mal typé en entrée. Je corrigerai post merge avant de faire la release.
J'ai vu de petites fautes d'orthographe aussi que je corrigerai post merge ainsi que la suppression du fichier .DS_Store.

2021-02-20 20:54 UTC, merged

2021-02-20 20:59 UTC, cnico commented
Voilà, c'est mergé.
Je vais corriger 2-3 détails avant la réalisation de la nouvelle version et sa publication comme indiqué dans la revue.

Pour ton info, moi aussi, je débute en python et dev homeassistant (je suis issu du monde Java et m'y suis mis il y a juste 2-3 semaines).

Concernant la réalisation de l'intégration flipr, j'ai trouvé ça plus dur car ça tire la compréhension des apis de homeassistant. Il te faudra attendre que ma PR soit validée pour pouvoir en proposer une à la communauté homeassistant je pense (ils ont dans leur guide line le fait de demander de plusieurs petites évolutions plutôt qu'une grosse).
Bon courage à toi.

2021-02-20 22:11 UTC, AntorFr commented
Super merci beaucoup.